version: '3.3'

volumes:
  pg_data:
  static_data:
  media_data:

services:

  db:
    image: postgres:13.10
    env_file:
      - ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    image: danilkas/foodgram_backend
    env_file:
      - ./.env 
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - static_data:/static/
      - media_data:/media/

  frontend:
    image: danilkas/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend 

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_data:/var/html/static/
      - media_data:/var/html/media/
    depends_on:
      - frontend     
      - backend
