# Generated by Django 3.2 on 2023-11-02 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_tags_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='description',
            field=models.CharField(max_length=1500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='color',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='Цвет тэга должен быть в формате #RRGGBB!', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Цвет'),
        ),
    ]
