# Generated by Django 3.2 on 2023-11-02 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20231102_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Цвет тэга должен быть в формате #RRGGBB!', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Цвет'),
        ),
    ]
