# Generated by Django 3.2 on 2023-11-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_tags_color'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredients',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='ingredient_name_unique'),
        ),
    ]
